### PR TITLE
SDRClassifier: fix precision by using Real64 for PDF

### LINKED ISSUE #646: SDRClasifier for Prediction?
Hi David @ctrl-z-9000-times 
I am looking at your Predictor now.
If I understood you well, this function will be used for prediction any data, based on SDR-pattern.
I really do not understand what does "recordNum" mean exactly for infer and learn?
```
Predictions infer(UInt recordNum, const SDR &pattern);
void learn(UInt recordNum, const SDR &pattern, const std::vector<UInt> &bucketIdxList);
```
if I have 1D data like a vector v = {1.1, 5, 3, 9 ...}.
Is it a data index, or frame index? e.g. SDR for v[0] = 1.1, recordNum = 0?

Secondly: 
If I use it for predict a 1D data, I think bucket index is not enough for this purpose, because Inference provides only the bucket index, not the real value.
To bring the full performance of Predictor like decode(), by learning we have to input a map of bucket and real value like
```
std::map<UInt, Real32> data; // 1st for bucket, 2nd for value
```
Do you think that we should do it in Predictor-class or user have to map them individually?
Thanks

EDIT:
The problem seems to be in insuffucient precision of Real, and Real64 should be used for PDF in SDRClassifier/Predictor. No test to replicate, though. https://github.com/htm-community/htm.core/issues/646#issuecomment-525402943

### PR DESCRIPTION
**Pull request by breznak**
without this, the scores never correctly converge(learn).
Thanks @Thanh-Binh for finding and solving this bug.

Additionally, add some docs to the class.

Fixes #646 

TODO:
- [ ] We need a test to replicate the reported issue before this is merged

### CODE REVIEW

File: src/htm/algorithms/SDRClassifier.cpp [hunk 1]
```diff
@@ -165,13 +169,12 @@ void Predictor::reset() {
 }
 
 
-Predictions Predictor::infer(const UInt recordNum, const SDR &pattern)
-{
-  updateHistory_( recordNum, pattern );
+Predictions Predictor::infer(const UInt recordNum, const SDR &pattern) const {
+  checkMonotonic_(recordNum);
```
Comment (breznak) [inline src/htm/algorithms/SDRClassifier.cpp]: @ctrl-z-9000-times please have a look on the last 1,(2) commits, I intended to make `infer` const, as it imho should have been. For Classifier that was easy, for Predictor I had to remove the `updateHistory_` from infer (no tests visibly broken).

File: src/htm/algorithms/SDRClassifier.hpp [hunk 2]
```diff
@@ -21,6 +21,13 @@
 
 /** @file
  * Definitions for the SDR Classifier & Predictor.
+ * 
+ * `Classifier` learns mapping from SDR->input value (encoder's output). This is used when you need to "explain" the HTM network back to real-world, ie. mapping SDRs
```
Comment (ctrl-z-9000-times) [inline src/htm/algorithms/SDRClassifier.hpp]: Nitpick: It's hard to read lines which are this long...

File: src/htm/algorithms/SDRClassifier.cpp (hunk 1 above)
Comment (ctrl-z-9000-times) [reply src/htm/algorithms/SDRClassifier.cpp]: Why does it matter if infer is constant?  I doubt it will have any performance impact, and I don't think this will prevent any programming mistakes.

Consider the following chain of events:
```
infer( t, SDR-A ) -> PDF
learn( t+1, SDR-B, Labels )
```
The method `updateHistory` stores the given SDR inside of the predictor.  Previously the call to `learn` would have associated `SDR-A` with `Labels` since that SDR was given to infer with.  Now that will not happen.

Also, these changes allow the timestamps to the infer method to go backwards.
```
infer( t + 2, ... )
infer( t, ... )
```

I'm not saying the new behavior is *wrong*, just that it changed.

Comment (breznak) [reply src/htm/algorithms/SDRClassifier.cpp]: >  I doubt it will have any performance impact, and I don't think this will prevent any programming mistakes.

right, there won't be any performance gains, and the behavior has changed. I think it adds (expected) semantics, and better separates responsibilities of those 2 functions: 
- you know only what you `learn()` 
- and you can `infer() const` anytime without any worry of changing the state (comes with loosened requirement for monotonic timestamps)

File: src/htm/algorithms/SDRClassifier.hpp (hunk 2 above)
Comment (ctrl-z-9000-times) [reply src/htm/algorithms/SDRClassifier.hpp]: Thanks.  As a general rule of thumb, if I expect people to read something then it should be no more than 80 characters per line.  I think it improves readability.  This is important for documentation, but less so for source code.

File: src/htm/algorithms/SDRClassifier.cpp (hunk 1 above)
Comment (ctrl-z-9000-times) [reply src/htm/algorithms/SDRClassifier.cpp]: Ok, that makes sense +1

**Comment by breznak** [comment]
@Thanh-binh Can you please test that this branch fixes the problem with Predictor you describe in #646 ? 

Also, how is going your work on publishing the reproducible example for this issue? In the meanwhile, I'll try to add Predictor to the hotgym example (that also uses sine waves).

**Comment by Thanh-Binh** [comment]
@breznak 
I think the crash problem comes from the fact that you remove
updateHistory_( recordNum, pattern );
in the function infer().

**Comment by breznak** [comment]
> I think the crash problem comes from the fact that you remove
updateHistory_( recordNum, pattern );

the strange thing is debug mode (and gdb) is not able to detect/crash, that's a strange issue. 
I can look into this. 

A different solution would be removing recordNum altogether. I find it unneeded for the inference (maybe also learn) where I want to set a SDR and predict N-th next pattern/label. https://github.com/htm-community/htm.core/pull/675#discussion_r325598269

File: src/htm/algorithms/SDRClassifier.cpp [hunk 3]
```diff
@@ -165,56 +161,49 @@ void Predictor::reset() {
...
   for( const auto step : steps_ ) {
-    result[step] = classifiers_[step].infer( pattern );
+    result.insert({step, classifiers_.at(step).infer( pattern )});
   }
   return result;
 }
 
 
-void Predictor::learn(const UInt recordNum, const SDR &pattern,
+void Predictor::learn(const UInt recordNum, //TODO make recordNum optional, autoincrement as steps
```
Comment (breznak) [inline src/htm/algorithms/SDRClassifier.cpp]: for sequential use, even in `learn()` recordNum could be made optional

Comment (ctrl-z-9000-times) [reply src/htm/algorithms/SDRClassifier.cpp]: Yea, `recordNum` is only useful if the user wants to _skip_ time steps, which is not the common case.  However when working with time series data sets, there are valid situations where you don't want to learn about a specific time-step so we should keep the time-skip capability in some form.

**Comment by breznak** [comment]
Thanks for reviewing, followup TODOs are: 
- [ ] Predictor.learn(): make arg recordNum optional
- [ ] fix crash with too large category, seen in #675

**Comment by Thanh-Binh** [comment]
@breznak I do not think if remove updateHistory() from infer() is good idea, because it is thought for dynamically changing the learn and inference mode in the real-time.

**Comment by breznak** [comment]
> if remove updateHistory() from infer() is good idea, because it is thought for dynamically changing the learn and inference mode in the real-time. 

I don't understand, can you explain, please? 
See https://github.com/htm-community/htm.core/pull/667#discussion_r325221594 for why I think the new behavior is more correct. You can call learn/infer at anytime, recordNum has nothing to do with it. Do you have a usecase where the current functionality is insufficient?
