### PR TITLE
fix comparison on ARM

### LINKED ISSUE #722: Broken ARM build: Value.cpp
Recent changes in Value, 
https://github.com/htm-community/htm.core/commit/0fa85d805254c18df309ec84a0ad6c6526b367f3/checks?check_suite_id=276967312#step:4:537

### PR DESCRIPTION
**Pull request by breznak**
Fixes #722

### CODE REVIEW

File: src/htm/ntypes/Value.cpp [hunk 1]
```diff
@@ -610,10 +611,10 @@ static void escape_json(std::ostream &o, const std::string &s) {
       o << "\\t";
       break;
     default:
-      if ('\x00' <= *c && *c <= '\x1f') {
-        o << "\\u" << std::hex << std::setw(4) << std::setfill('0') << (int)*c;
+      if ('\x00' <= sc && sc <= '\x1f') {
```
Comment (dkeeney) [inline src/htm/ntypes/Value.cpp]: I think this logic is wrong...not the sign of c.
What this should be doing is converting non-printing and non-ASCII characters to hex.
So it should be
```
if ('\x20' < *c && *c >= '\x1f') {
```

Comment (breznak) [reply src/htm/ntypes/Value.cpp]: > if ('\x20' < *c && *c >= '\x1f')

is that correct? It's just a complicated way to `*c == '\x1f'`

Comment (dkeeney) [reply src/htm/ntypes/Value.cpp]: Oops. That is really wrong.  Dyslexia I guess.
What it should do is be true for 0 through \x1f and \x7f to \xff.
So that would be 
```
if ("\x1f" <= *c || *c >= "\x7f")
```
Do I have it right this time?

Comment (dkeeney) [reply src/htm/ntypes/Value.cpp]: No, I still have it wrong.  I looked up the standard for JSON (https://www.json.org/)
and it uses \u with 4 hex characters.  Let me figure out what this needs to be.

Comment (breznak) [reply src/htm/ntypes/Value.cpp]: > No, I still have it wrong. I looked up the standard for JSON

oh, pused the former fix for the correct ranges, handing over to you now :smiling_imp:

Comment (dkeeney) [reply src/htm/ntypes/Value.cpp]: It says "Any codepoint except " or \ or control characters."
So that means that it allows non-ASCII characters.  If we are using UTF8 which I assume we are then escaping multibyte characters individually could confuse it.
So that means just he control characters 0 - 0x1f  and the one character 0x7f

```
if (0x1f <= *c || *c == 0x7f)
```

Comment (dkeeney) [reply src/htm/ntypes/Value.cpp]: Ok, I messed it up to start with.  So let me try to fix it.

**Comment by breznak** [comment]
> I think I have it right this time. Lets see if the ARM compile likes it.

thanks, merging, ARM will only run on schedule on master. (I'll test this locally if I get to it earlier too)
